server:
  port: 8082
spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.spirit.community.wx
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:dao/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql
logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.wx:  DEBUG
    org.linlinjava.litemall:  ERROR